@startuml
actor User
participant ":Ui" as Ui
participant ":Parser" as Parser
participant ":ListCommand" as ListCommand
participant ":TransactionList" as TransactionList

User -> Ui : enter "list"
Ui -> Parser : parse("list")
Parser --> Ui : ListCommand
Ui -> ListCommand : execute(list, ui)
ListCommand -> TransactionList : isEmpty()

alt list is empty
    ListCommand -> Ui : showMessage("No transactions found.")
else list not empty
    loop for each transaction
        ListCommand -> TransactionList : get(i)
        TransactionList --> ListCommand : transaction
        ListCommand -> Ui : showMessage(...)
    end
end
@enduml